apiVersion: harvesterhci.io/v1beta1
kind: Addon
labels:
  addon.harvesterhci.io/experimental: "true"
metadata:
  name: harvester-seeder
  namespace: harvester-system
spec:
  chart: harvester-seeder
  enabled: false
  repo: http://harvester-cluster-repo.cattle-system.svc/charts
  valuesContent: |
    image:
      tag: v0.3.0
    fullnameOverride: harvester-seeder
  version: 0.3.0
