apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: vm-import-controller
  namespace: harvester-system
spec:
  chart: harvester-vm-import-controller
  enabled: false
  repo: http://harvester-cluster-repo.cattle-system.svc/charts
  valuesContent: |
    image:
      tag: v0.3.0
    fullnameOverride: harvester-vm-import-controller
  version: 0.3.0
